services:
  streamlit1:
    build: ./striking
    ports:
      - "8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - ./striking/frequency_data:/striking/frequency_data
      - ./striking/frequency_data:/striking/saved_touches

  streamlit2:
    build: ./striking
    ports:
      - "8502"
    environment:
      - STREAMLIT_SERVER_PORT=8502
    volumes:
      - ./striking/frequency_data:/striking/frequency_data
      - ./striking/frequency_data:/striking/saved_touches
  streamlit3:
    build: ./striking
    ports:
      - "8503"
    environment:
      - STREAMLIT_SERVER_PORT=8503
    volumes:
      - ./striking/frequency_data:/striking/frequency_data
      - ./striking/frequency_data:/striking/saved_touches
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - streamlit1
      - streamlit2
      - streamlit3